name: "Build Kernel."                                 # Description of the workflow.
on:
  push:
    branches: master                                  # Branch to build.
  workflow_dispatch:                                  # Allow to manually trigger workflow.
jobs:
  build:
    name: "Build kernel"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout kernel source"                  # Clone the kernel source.
      uses: actions/checkout@v2
    - name: "Checkout zipper"                         # (OPTIONAL) Clone the AnyKernel3 template.
      uses: actions/checkout@v2
      with:
        repository: a02-trial/AnyKernel3              # Your own AnyKernel3 repository.
        path: zipper                                  # Clone to path "zipper", REQUIRED.
    
    - name: Android kernel build
      uses: lemniskett/android-kernel-actions@master
      id: build
      env:
        NAME: RooXie
      with:
        arch: arm
        compiler: gcc/10
        defconfig: a02_defconfig
        image: zImage

    - name: Release build
      uses: ncipollo/release-action@main
      with:
        artifacts: ${{ steps.build.outputs.outfile }}
        token: ${{ secrets.GITHUB_TOKEN }}
